### ISSUE TITLE
Solr : schema.xml should be add a line about "groups"

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub-modules-solr#1]
Solr module give a error message like bellow:

Could not execute solr add query:Solr HTTP error: OK (400)
{
  "responseHeader":{
    "status":400,
    "QTime":10},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"ERROR: [doc=humhub\\modules\\user\\models\\User---4] multiple values encountered for non multiValued field groups: [2, 13]",
    "code":400
  }
}

I'd have written a line to /var/solr/data/humhubcore/conf/schema.xml, that error stopped.

<field name="groups" type="long" indexed="true" multiValued="true" required="false" stored="false"/>

How about Solr module should be with that line?

**Comment by luke-** [comment]
Thank you for pointing that out. Do you have an example schema.xml?

In the current master the bug is fixed so that the group ids are not indexed at all.

**Comment by tomofu74** [comment]
Yes, I have an example. Should I upload it here?

**Comment by luke-** [comment]
@tomofu74 An example of your schema.xml would be great. We then add this to the offficial docu.

**Comment by tomofu74** [comment]
My Scheme.xml will be irrelevant if you modified the system to unindexed the groups.
Because I just added a line that says indexed=true, Multivalued=true to the fields declaration of groups.
It is only a temporary surpass.

<field name="groups" type="long" indexed="true" multiValued="true" required="false" stored="false"/>

I believe your modification is the best. Thank you.

**Comment by luke-** [comment]
Thats right. 

It's fixed with solr module 1.1.1

Thanks!
